In [1]:
import json
import pandas as pd

%matplotlib inline
import matplotlib.pyplot as plt

import seaborn as sns
sns.set(color_codes=True)

In [10]:
d4 = pd.read_csv('~/Desktop/mort2004.csv', nrows=10**4, dtype=object)

pd.options.display.max_rows = 999
pd.options.display.max_columns = 100

### useful info
For column definitions, see: http://www.nber.org/mortality/2003/mort2003.log

For reading in really large csv files: https://stackoverflow.com/questions/25962114/how-to-read-a-6-gb-csv-file-with-pandas

In [8]:
d4.head()

,rectype,restatus,stateoc,countyoc,exstatoc,popsizoc,staters,statersr,countyrs,cityrs,popsize,metro,exstares,pmsares,popsizrs,popmsa,cmsares,statbth,statbthr,educ89,educ,educflag,monthdth,sex,age,ageflag,ager52,ager27,ager12,ager22,placdth,marstat,weekday,year,injwork,mandeath,methdisp,autopsy,activity,injury,ucod,ucr358,ucr113,ucr130,ucr39,eanum,econdp_1,econds_1,enicon_1,econdp_2,...,enicon_13,econdp_14,econds_14,enicon_14,econdp_15,econds_15,enicon_15,econdp_16,econds_16,enicon_16,econdp_17,econds_17,enicon_17,econdp_18,econds_18,enicon_18,econdp_19,econds_19,enicon_19,econdp_20,econds_20,enicon_20,ranum,record_1,record_2,record_3,record_4,record_5,record_6,record_7,record_8,record_9,record_10,record_11,record_12,record_13,record_14,record_15,record_16,record_17,record_18,record_19,record_20,race,brace,raceimp,racer3,racer5,hispanic,hspanicr
0,2,2,MA,MA025,MA,1,MA,MA,MA027,99999,9,1,MA,1123,1,1,7,MI,MI,16,NaN,0,1,M,1038,NaN,33,13,6,NaN,1,M,5,2004,N,7,U,N,NaN,NaN,C439,98,28,NaN,15,1,1,1,C439,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,C439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
1,2,2,MA,MA025,MA,1,MA,MA,MA021,99999,9,1,MA,1123,1,1,7,MA,MA,10,NaN,0,1,M,1049,NaN,35,15,7,NaN,4,D,5,2004,N,5,U,Y,9,9,Y12,443,133,NaN,42,2,1,1,T403,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,T403,Y12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
2,2,2,MA,MA025,MA,1,MA,MA,MA017,99999,9,1,MA,1123,0,1,7,MA,MA,10,NaN,0,1,M,1054,NaN,36,16,7,NaN,2,S,6,2004,U,7,U,N,NaN,NaN,R090,380,110,NaN,36,1,2,1,R090,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,R090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
3,2,2,MA,MA025,MA,1,MA,MA,MA027,99999,9,1,MA,1123,1,1,7,ZZ,CC,6,NaN,0,1,M,1054,NaN,36,16,7,NaN,1,M,5,2004,U,7,U,Y,NaN,NaN,I429,227,68,NaN,22,3,1,1,J189,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,D65,I429,J189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,100,6
4,1,1,MA,MA025,MA,1,MA,MA,MA025,07000,1,1,MA,1123,1,1,7,ZZ,YY,12,NaN,0,1,M,1061,NaN,38,18,8,NaN,2,M,5,2004,U,7,U,N,NaN,NaN,I251,215,63,NaN,21,2,1,1,I469,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,I251,I469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,3,2,100,7

In [ ]:
# decide which cols to use
cols = ['countyoc','countyrs','staters','metro','educ89','educ','educflag','sex','age','marstat','weekday','year',]